const { GoogleGenerativeAI } = require('@google/generative-ai');
const fs = require('fs');

/**
 * AI Code Review Logic
 *
 * This script reads a git diff from 'diff.txt', sends it to Gemini for analysis,
 * and writes the result to 'review_comment.md'.
 */
async function run() {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY is missing from environment');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    // Force v1 API to avoid 404s on v1beta in certain regions
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' }, { apiVersion: 'v1' }); 


    // Read the diff generated by the workflow
    if (!fs.existsSync('diff.txt')) {
      console.log('No diff.txt found. Skipping review.');
      return;
    }

    const diff = fs.readFileSync('diff.txt', 'utf8').slice(0, 20000); // Increased limit slightly
    if (!diff.trim()) {
      console.log('Diff is empty. Skipping review.');
      return;
    }

    const prompt = `You are a senior code reviewer. Analyze this code diff. 
Identify any bugs, logic errors, security vulnerabilities, or performance bottlenecks. 
If the code looks great, say so. 
Provide a concise, helpful review in Markdown format.

Code Diff:
${diff}`;

    console.log('Generating AI review...');
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    fs.writeFileSync('review_comment.md', text);
    console.log('Review generated successfully and saved to review_comment.md');
  } catch (error) {
    console.error('Error in AI Review Logic:', error.message);
    process.exit(1);
  }
}

run();
